import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import MobileMenu from "@/components/MobileMenu";

const roboto = Roboto({ weight: "400", subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased flex gap-2 max-md:flex-col`}>
        <Sidebar />
        <div className="sticky top-0 h-10 flex justify-between items-center px-3 shadow-md md:hidden bg-white">
          <MobileMenu />
          <span className="font-semibold w-full text-right">
            Banking System
          </span>
        </div>
        {children}
      </body>
    </html>
  );
}
